### ISSUE TITLE
auto-detect network type when using drcwallet rpc

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#100]
This is one of 2 efforts to eliminate the need for a network type flag/option in godcr. The other effort is described in #89. Fixing this issue and #89 should totally render the `testnet` config flag unnecessary and the flag should be removed.

There are 2 current usages of the `testnet` flag in dcrwallet rpc:
- For "constructing" a dcrwallet rpc server address if user does not provide one. [See here](https://github.com/raedahgroup/godcr/blob/master/app/walletmediums/dcrwalletrpc/dcrwalletrpc.go#L71).
- For defining the network parameters for the connected wallet. [See here](https://github.com/raedahgroup/godcr/blob/master/app/walletmediums/dcrwalletrpc/dcrwalletrpc.go#L56). The defined network parameter is used by different core wallet functions to differentiate addresses and keys for one network from those intended for use on another network.

For the first use case, if the user does not provide a rpc server address, the immediate solution is to display an error message to the user, asking the user to set the dcrwallet rpc server address in config file. See #152

For the second use case, the network type can be determined once godcr is successfully connected to dcrwallet via gRPC. [See this](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#network). Once the network type is determined, the network params can be defined.

**Comment by barisere** [comment]
[The wallet RPC method linked to](https://github.com/decred/dcrwallet/blob/master/rpc/documentation/api.md#network) is unstable for now. Should we depend on it?
> Stability: Unstable: This may be moved to another service as it does not depend on the wallet.

**Comment by itswisdomagain** [comment]
Most RPC methods in that doc are said to be unstable, even for getting account balance. We can work with it until we meet a bug, but I don't expect we will
