### ISSUE TITLE
add cli command to create config file

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#107]
Once #106 is completed, we'll have a clearer idea of what options and flags ideally belong to the config file. A `godcr config` command that provides an interactive way for a user to create a config file.

The command should prompt the user for values for all the options/flags that should be in config, providing default values for each option/flag. If there is no default value for a particular option/flag, and the user does not provide a value for that option/flag, the option should be included in the config file without a value, but commented out.

#64 has some context that can bring this to life

**Comment by raedah** [comment]
the —detect  cmd for autoconfiguration will be taking care of the config once we get to that.
