### ISSUE TITLE
Add flags options to pass configuration parameters

### ISSUE THREAD

**Issue by boscobass** [raedahgroup/godcr-old#11]
The dcrcli settings parameters are all centered in the dcrcli.conf file. It would be nice to have the option to pass flags with the parameters via terminal.

Example:

$ ./dcrcli accounts --rpcuser xxx --rpcpass **** --cert /path/to/cert.pen

**Comment by boscobass** [comment]
i'll do this issue

**Comment by Jujhar** [comment]
Hi @codemaestro64 this may have been fixed?

**Comment by yaowork** [comment]
@Jujhar not yet.

**Comment by yaowork** [comment]
@Jujhar you were right. This has been a feature from the project's beginning. 

Closing
