### ISSUE TITLE
auto-detect dcrwallet rpc server address

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#152]
This issue applies to scenarios where a user runs godcr with `usewalletrpc=true`, but does not provide a dcrwallet rpc server address

- Currently, an address is "constructed" using the `testnet` config flag. [See here](https://github.com/raedahgroup/godcr/blob/master/app/walletmediums/dcrwalletrpc/dcrwalletrpc.go#L71)
- After a fix to #100 is merged, a "default" address will no longer be constructed, instead an error message will be displayed to the user

The desired behaviour is to try to "detect" the rpc server address before showing the user an error message, if an address cannot be detected.

Here are some ideas to explore for auto-detecting dcrwallet rpc server address:

1. Check running processes to see if dcrwallet is currently running. If it is, determine the address (host and port) that the running dcrwallet process is bound to.

2. Attempt to connect to dcrwallet using a [testnet-constructed address](https://github.com/raedahgroup/godcr/blob/master/app/walletmediums/dcrwalletrpc/dcrwalletrpc.go#L73). If that doesn't connect, perform a second connection attempt using a [mainnet-constructed address](https://github.com/raedahgroup/godcr/blob/master/app/walletmediums/dcrwalletrpc/dcrwalletrpc.go#L75)

3. Locate and parse the dcrwallet config file to determine the dcrwallet rpc server address configured by the user. See [here](https://github.com/decred/dcrwallet/blob/master/config.go#L78) for the default path to the config file, and [here](https://github.com/decred/dcrwallet/blob/master/sample-dcrwallet.conf#L93-L107) for how to extract the address from the config file.

Each of the above possibilities have their strengths and weaknesses, it _might_ be a good idea to combine multiple approaches in a bid to auto-detect the dcrwallet rpc server address.

However it is very possible that a **valid** rpc server address cannot be detected - perhaps because the user has not started the dcrwallet daemon or probably doesn't even have the dcrwallet binary. Whatever the case, the user should be asked to confirm that dcrwallet is running and if it is running, the user should be allowed to set the rpc server address directly from the terminal.

```
> Could not detect a valid rpc address to connect to dcrwallet
> Do you want to set the address now? [y/n]: y
> Enter dcrwallet rpc address: 127.0.0.1:19111
> rpc address saved, connecting...
```

Or

```
> Could not detect a valid rpc address to connect to dcrwallet
> Do you want to set the address now? [y/n]: n
> Okay. Bye.
> You can also set the rpc address later in ~/godcr/godcr.conf
```

**Comment by barisere** [comment]
I'm inclined to do only the minimum necessary to have a graceful failure. If the user does not provide a dcrwallet rpc server address, a default is fine. Many applications adopt a default port for the simplicity (convention over configuration); Apache, Nginx, MongoDB, and even `dcrwallet` and `dcrd`. I guess not every user is interested in fiddling with configuration.
We can assume localhost and the default port for `dcrwallet` if no rpc server address was specified. If connection fails, we let the user know that no rpc server address was specified, and that our attempt to connect via the default failed (which means the user either does not have `dcrwallet` running, or is running `dcrwallet` on a different network address).
Most users may use `dcrlibwallet` since that is supported and does not require other daemon programs. Users that are interested in using `dcrwallet` will get familiar with setting it up.
>Attempt to connect to dcrwallet using a testnet-constructed address. If that doesn't connect, perform a second connection attempt using a mainnet-constructed address

We can do that in addition to using the default network address for `dcrwallet`, because the user can run `dcrwallet` with either mainnet or testnet.

**Comment by itswisdomagain** [comment]
> I'm inclined to do only the minimum necessary to have a graceful failure

As mentioned in the issue description, `the desired behaviour is to try to "detect" the rpc server address before showing the user an error message, if an address cannot be detected`. The ideas provided are simple possibilities worth considering, leaving room for some creativity. Anything that achieves the stated objective well enough, will be accepted.

> Many applications adopt a default port for the simplicity (convention over configuration); Apache, Nginx, MongoDB, and even `dcrwallet` and `dcrd`. I guess not every user is interested in fiddling with configuration

True, but all those applications listed are primarily developer-facing, not regular-user-facing, `godcr` is primarily for the regular user, so we should remain committed to doing what works best for the regular user, even if it means more code.

> We can assume localhost and the default port for `dcrwallet` if no rpc server address was specified. If connection fails, we let the user know that no rpc server address was specified, and that our attempt to connect via the default failed (which means the user either does not have `dcrwallet` running, or is running `dcrwallet` on a different network address)

- That's one of the suggested options worth trying. There are 2 defaults though, so both will have to be tried before notifying the user
- If both fails but the user is indeed running dcrwallet (likely passed a different address in dcrwallet command-line option) and we can detect the address for that running process, I think we should too. But again, left to the discretion of whoever takes up this issue

> Most users may use `dcrlibwallet` since that is supported and does not require other daemon programs. Users that are interested in using `dcrwallet` will get familiar with setting it up.

Most users **may** use `dcrlibwallet`, yeah. All the same, if it won't take too much to make `godcr` more user-friendly for the other group of users, we should probably do so. I still prefer to leave that to the discretion of whoever takes up this issue. Really don't want to be stringent on **how** the fix should be implemented

> > Attempt to connect to dcrwallet using a testnet-constructed address. If that doesn't connect, perform a second connection attempt using a mainnet-constructed address
> 
> We can do that in addition to using the default network address for `dcrwallet`, because the user can run `dcrwallet` with either mainnet or testnet.

Is there another default network address for `dcrwallet` aside those 2? Not sure, the default is either the "testnet-constructed address" or the "mainnet-constructed address", but if there is some other default, that should definitely be tried first

We also do not want to disregard parsing the dcrwallet config file because any address set there by the user is what will be used regardless of the network type, thus eliminating the need to try 2 possible addresses for different network types. If an address can be parsed from the config, it definitely should be tried before attempting to use either testnet or mainnet default

By the way, what I surmise from your comment @barisere is that if rpc server address is not set, we should stick to simply trying the default address for testnet and if that doesn't work, we try the default address for mainnet and if that fails also, we tell the user we've tried our best. Is my understanding correct?
