### ISSUE TITLE
webpack bundle exceeds the 244kb limit

### ISSUE THREAD

**Issue by ademuanthony** [raedahgroup/godcr-old#297]
Running th `yarn build` command currently gives a warning.

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
```
app (248 KiB)
      js/vendors~app.bundle.js
      js/app.bundle.js```

**Comment by jondavidjohn** [comment]
I built a tool to help you analyze webpack bundles for size regressions, and report them directly to GitHub PRs. It's free for open source, so it might be worth checking out and helpful in this scenario.

[https://packtracker.io](https://packtracker.io/?utm_campaign=links&utm_source=github&utm_medium=issueprcomment)

![image](https://user-images.githubusercontent.com/401520/58719965-8ae35c80-8396-11e9-908d-5c5b1d7b8cbf.png)
