### ISSUE TITLE
terminal, navigations

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#310]
First thing I notice when I load the terminal view is I can not use the arrow keys to navigate up and down the menu. This should be fixed. Cause seems to be that overview page is showing, but its not obvious because the highlighting makes it look like the control is still on the nav bar. The nav bar items should have a different type of highlight when actually selected as in use, versus when simply being selected by the cursor. Left and Right arrow keys should be able to open and close menus. Up and down arrows should work within opened menus rather then having to use the tab keys.

Esc key works but there is a large delay in its responsiveness. This should be fixed.

nav bar is showing keys but the keys only work when the nav bar is in focus. I suggest hiding the keys when they are not usable.

Border is shown around the nav bar which implies it is in focus. Set the border to be around whatever part of the screen is the currently focused pane.

ESC from the nav bar should prompt the user if they want to quit the app.

Accounts, Security, Settings pages say nothing. Should say coming soon at least.

**Comment by Sirmorrison** [comment]
> Left and Right arrow keys should be able to open and close menus. Up and down arrows should work within opened menus rather then having to use the tab keys.

This will lead to a whole lot of conflicts as the arrow keys and tab key are default keys used by rivo/tview library for navigating between primitive fields (form fields, and page with multiple primitives) and primitive field contents (dropdown menus, scrolling tables, and pages).

>First thing I notice when I load the terminal view is I can not use the arrow keys to navigate up and down the menu. This should be fixed. Cause seems to be that overview page is showing

by default terminal renders the over view page when the app is loaded hence that behavior. if we are not to render the overview page then the navigation will be navigable when the application is loaded but no page will be rendered until the user selects a menu option.
