### ISSUE TITLE
terminal, history view bug

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#311]
Is not showing a full screen worth of transactions on first view. Once scrolled down to the next page, then the screen properly fills with transactions.

Columns are changing width each page. This is not ideal. Fixed size is preferred.

Spacing between columns should be increased. Someone said the toolkit does not support this. If so, we should file an upstream issue.

Show the total count of transactions at the top of the page.

**Comment by Sirmorrison** [comment]
>Show the total count of transactions at the top of the page.

this task will be fixed with #280 reason is @itswisdomagain is working on tx indexing which will make tx counting possible.

**Comment by raedah** [comment]
closed by https://github.com/raedahgroup/godcr/pull/327
