### ISSUE TITLE
godcr wallet selection at startup

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#315]
When godcr is first executed it should show a list of all available wallets on the system and allow the user to select which one to use for that session. This can happen at the command line and would be prior to the interface being launched that is choosen.

**Comment by itswisdomagain** [comment]
- Currently, if there is no wallet configured for use, user is asked whether to detect wallets. Should this prompt be removed only on first run? Or whenever godcr cannot find a wallet to connect to?

- If a wallet was previously configured but the file can no longer be found, should the user be prompted to 
  - re-detect wallets
  - create new wallet (at command line)
  - create new wallet (after launching interface)
  - or proceed to re-detect wallets without prompting user
