### ISSUE TITLE
Generate Receive Address Error with imported account

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#32]
When dcrwallet creates a wallet on first run, the wallet has 2 accounts
- default (account number 0)
- imported (account number 2147483647)

Attempting to generate receive address for the imported account (for example via cli: `dcrcli receive 2147483647`) returns the following error: 

`wallet.NewExternalAddress: item does not exist: account 2147483647`

**Comment by Jujhar** [comment]
Working on this.

**Comment by itswisdomagain** [comment]
An explanation for this issue/error is provided in [this comment](https://github.com/raedahgroup/dcrcli/pull/33#issuecomment-438644474) in #33
