### ISSUE TITLE
wrong amount unit for cli send command

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#37]
`dcrcli send` asks for amount in DCR but amount debited is not in DCR. This issue has been fixed for the web server package in PR #30, specifically in [this comment](https://github.com/raedahgroup/dcrcli/pull/30/commits/174385aae1a6973615adbc7b8cca001c0e64ade4), just to replicate in the cli package

**Comment by yaowork** [comment]
We should probably fix this in the walletrpcclient package. Any value passed should be converted by doing amount*10^8 there.

**Comment by barisere** [comment]
> We should probably fix this in the walletrpcclient package. Any value passed should be converted by doing amount*10^8 there.

Looking at the signature of the `Send` method in the walletrpcclient package, it seems to expect amount to be an `Amount`, although it says `int64` in the signature.

`func (c *Client) Send(amount int64, sourceAccount uint32, destinationAddress, passphrase string) (*SendResult, error)`.

If that is the case, the fix should be to convert the amount from `int64` to `Amount` in `cli.go` by calling `dcrutil.NewAmount()`, so from https://github.com/raedahgroup/dcrcli/blob/2a8079b617a52caf8ab5703e645d47e3368e73de/cli/cli.go#L219
```go
func (c *CLI) send(commandArgs []string) (*response, error) {
        // ...
	sendAmount, err := getSendAmount()
	if err != nil {
		return nil, err
	}

	passphrase, err := getWalletPassphrase()
	if err != nil {
		return nil, err
	}

	result, err := c.walletrpcclient.Send(sendAmount, sourceAccount, destinationAddress, passphrase)
	if err != nil {
		return nil, err
        }
        // ...
}
```
becomes
```go
func (c *CLI) send(commandArgs []string) (*response, error) {
        // ...
		amount, err := getSendAmount()
	if err != nil {
		return nil, err
	}
	sendAmount, err := dcrutil.NewAmount(float64(amount))
	if err != nil {
		return nil, err
	}
	fmt.Printf("%+v, %+v\n", sendAmount, int64(sendAmount))

	passphrase, err := getWalletPassphrase()
	if err != nil {
		return nil, err
	}

	result, err := c.walletrpcclient.Send(int64(sendAmount), sourceAccount, destinationAddress, passphrase)
	if err != nil {
		return nil, err
	}
        // ...
}
```

The double cast (to and from `float64`) will be removed if `getSendAmount` is updated to return a `float64`. Currently `getSendAmount` does not return `float64`, which means users cannot send coins in fractional units.

**Comment by barisere** [comment]
I tried my suggestion above and logged the value of `sendAmount` in both `Amount` and `int64` formats.
```go
fmt.Printf("%+v, %+v\n", sendAmount, int64(sendAmount))
```
I get the following.
>199 DCR, 19900000000

But sending 199 DCR sends only 0.000419 DCR. Maybe the problem is not in the `send` method?

**Comment by itswisdomagain** [comment]
Thanks for leaving these thoughts. I'll test from my end as well and revert

**Comment by itswisdomagain** [comment]
According to the dcrutil docs, https://godoc.org/github.com/decred/dcrd/dcrutil#NewAmount, your code above should work.

This converts the user input (which is the amount in DCR) to the equivalent amount in atoms (which is what `dcrwallet` needs.
`sendAmount, err := dcrutil.NewAmount(float64(amount))`

That command however returns the amount as a `dcrutil.Amount` type which, although being an int64 alias, cannot be used directly unless "converted" to int64, which you did here:
`result, err := c.walletrpcclient.Send(int64(sendAmount), sourceAccount, destinationAddress, passphrase)`

**Comment by itswisdomagain** [comment]
The above PR (#41) harmonizes the thoughts shared by @codemaestro64 by performing all necessary conversions in the `walletrpcclient` package
> We should probably fix this in the walletrpcclient package

and the thought by @barisere by accepting fractional amount input on both the cli and web interfaces.
> The double cast (to and from `float64`) will be removed if `getSendAmount` is updated to return a `float64`. Currently `getSendAmount` does not return `float64`, which means users cannot send coins in fractional units.

@barisere @codemaestro64 please test and review the PR and merge if all is good
