### ISSUE TITLE
make cli receive command interactive if account number is not provided

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#38]
Currently, `dcrcli receive` command requires account number argument and returns error message if no account number argument is supplied.

Seeing as users should not really be expected to memorize the account numbers for all the accounts in their wallet, it might help to give users a prompt to select the account they want to receive funds for. This functionality is already implemented in the web server package and similar functionality exists for the `dcrcli send` command as described in #10 

The `dcrcli receive` command should retain its ability to accept an account number argument though and should only prompt user for selection if no argument is provided or an invalid argument was provided

**Comment by Jujhar** [comment]
I got this
