### ISSUE TITLE
Pack static assets into release binaries for fyne UI

### ISSUE THREAD

**Issue by barisere** [raedahgroup/godcr-old#423]
The fyne UI depends on some PNG images that are used as icons on the UI. Previously they were read from a relative path on disk. That worked in development, but the images cannot be read when the binary is run from a different location on the filesystem.
A temporary workaround was introduced by @metaclips: the images were converted into bytes and hard-coded in the application. That workaround made its way into #419. 
However, hard-coding images as byte slices obscures the fact that they are images, and we cannot visually inspect the images on disk. We intend to restore the image files and, instead of hard-coding in the source code, pack them into the built binary using [Packr](https://github.com/gobuffalo/packr).
This issue will track the implementation of this approach across each interface where we adopt it.

**Comment by itswisdomagain** [comment]
@barisere, in line with the title of this issue, this issue should be limited to the fyne interface only. Once packr is implemented for fyne, this issue can be closed.
