### ISSUE TITLE
installation for the newbie

### ISSUE THREAD

**Issue by skynet0590** [raedahgroup/godcr-old#475]
Hi I am new on godcr. As a newbie, I am trying to get this repository run as well. But I get errors with go mod and version of imported packages. You can see in this image
![Screenshot from 2020-01-10 10-45-17](https://user-images.githubusercontent.com/54076217/72124248-9c61fd80-3396-11ea-8bdc-3efb103a3657.png)

**Comment by metaclips** [comment]
Hello, you can read up on installation on all interfaces here https://github.com/raedahgroup/godcr/blob/master/README.md#step-3-build-the-source-code

**Comment by skynet0590** [comment]
Okay. Thank you
