### ISSUE TITLE
balance command simple and detailed

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#49]
The balance command by default should have simple output, which is, just returning the Total. For the more detailed view, an argument would be passed.

This style would be duplicated across other UI's as well, with the default balance showing only the Total, and a detailed view being available by user selection.

**Comment by raedah** [comment]
If Spendable is different then Total, then display like this.

Total 978.1184554 DCR  (Spendable 64.17666807 DCR)

**Comment by ademuanthony** [comment]
I can't see the optional arg that should be passed if the user wants more information on the cli.
Same goes for the web; the option to select if more detail is required is still missing.

**Comment by itswisdomagain** [comment]
This issue has only been partially resolved. The required changes have not been implemented on web interface

**Comment by itswisdomagain** [comment]
Fix completed in #102
