### ISSUE TITLE
./dcrcli help

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#51]
Add a ./dcrcli help   command.  It will be a more verbose version of the simple help that is returned when just running  ./dcrcli  by itself. Also have  ./dcrcli help cmd  return just the extended help for that one command.

**Comment by itswisdomagain** [comment]
Getting `./dcrcli help cmd` to provide help content for the specified command only would be similar to (work the same way as) `./dcrcli cmd -h` or `./dcrcli cmd --help` as is done in most other cli applications...
