### ISSUE TITLE
sendcustom more features

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#55]
```
Destination Address 2 (or blank to continue):
[repeat until done]
How many change outputs would you like to use? (default: 1): 2
[if more then one was specified]
Use random amounts for the change outputs? (Y/n): y
Enter your spending passphrase: 
You are about to spend the input
9.423 DCR from TsgUAq54uZ6GW1VQwgjtgG7KB68pJwy73dJ (default)
and send it to
2.123 DCR to TsgQwgjtgG7KB68pJwyUAq54uZ6GW1V73dJ
1.123 DCR to TsgJwyUAq54uZ6GWQwgjtgG7KB68p1V83dJ
3.123 DCR to TsgJwyWQwgjtgG7KB68pUAq54uZ6G1V83dJ (change)
3.123 DCR to TsgJwyuZ6G1V8WQwgjtgG7KB68pUAq543dJ (change)
Do you want to broadcast it? (y/n): y
sent txid b5f844895a4e5b4e496929be0356e8435a8c30976d6bd59a29539fddd37fc9d7

```

**Comment by raedah** [comment]
When listing the spent outputs, show account, date, confirms.
Instead of showing the utxo id, show the Received with Address.
Sort by amount. Do not show the list be default. Have a (l)ist command.
By default auto pick the first best sized input, show it, and provide it as a default available selection.

**Comment by itswisdomagain** [comment]
1 thought @raedah, the feature to send to multiple addresses can also be used in regular send and also on the web ui for custom send. Should this issue extend to those as well? For clarity,

- Replicate the flow above in the web interface version of send custom
- For the cli and web interface for the _regular_ send feature, add support for specifying multiple destination addresses (and amount for each address)

**Comment by itswisdomagain** [comment]
Some observations from your initial comment:

- Supporting multiple destination addresses would require being able to specify the amount to send to each address
- If user choses to use more than 1 change output, what happens if they (1) chose to use random amounts for the change outputs (2) if they don't?
- Does (1) above spread the change equally across the change addresses, while (2) asks them to enter the amount they'd want sent to each change address?
- The change address(es) are all generated from the account specified at the start of the command, this is fine, yes?

**Comment by raedah** [comment]
Yes, it is essentially one feature for control of the inputs, and another feature for control of the outputs. They can be used where appropriate.

For multiple change addresses, random would cause all change amounts to be random (not equal), but the total of them would be equal to the actual change amount. If it's not random, then they could define the amounts, but it would still be required that they add up to the total amount.

The rest of your assumptions look correct.

**Comment by itswisdomagain** [comment]
This issue is broken down into smaller issues to make it easier to tackle, perhaps simultaneously across different interfaces.

The new issues: #113, #114 and #115
