### ISSUE TITLE
cleanup http send page

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#57]
![untitled](https://user-images.githubusercontent.com/15878246/49907044-69d09300-fe6c-11e8-96b4-dcf1b1a05503.png)

**Comment by raedah** [comment]
-Get rid of blue color, not sure if that is a button or a header.
-Get rid of green color on next button.
-Field widths should only be as wide as needed and no more.
-No reason to have two columns for fields. Use one column.
-If only one account is available, it should just be printed and not a widget.
-Needs a checkbox to spend unconfirmed.
-Needs a checkbox to use a custom transaction, rather then the button? on top right.
-Send button at top should be bold to show the current location ( and for other locations as well.)

**Comment by itswisdomagain** [comment]
> Needs a checkbox to spend unconfirmed

This will also be needed on cli, a new issue (#138) has been created for this purpose and this is no longer a requirement for this issue

> Needs a checkbox to use a custom transaction

Latest information on this requirement is to use a collapsible div for this purpose. This is to tally with other additional options to be added such as customizing change outputs described in #139 

Also, the cli interface has some improvements on how transaction inputs are selected from utxos. It might help to study the latest flow of the `sendcustom` cli command, especially in relation to how the utxos are displayed in a list for user selection.

There's also the feature to auto-select best sized input(s) recently added to the cli interface that the web interface could adopt (see #140).
