### ISSUE TITLE
transaction details view

### ISSUE THREAD

**Issue by raedah** [raedahgroup/godcr-old#69]
webui gets a transaction details page

cli can get a  showtransaction  cmd

UPDATE:
Cli command implemented in #83

**Comment by itswisdomagain** [comment]
Currently, when listing transactions, the webui links each transaction hash to decred explorer (testnet.dcrdata.org or mainnet.dcrdata.org). It should instead direct to the transaction details page

**Comment by barisere** [comment]
- What information will be displayed in the transaction details?
- What will the input to the command be? A transaction hash?

**Comment by itswisdomagain** [comment]
> * What information will be displayed in the transaction details?

Compare what's displayed on decred explorer (ex. https://testnet.dcrdata.org/tx/2d574a40dbc31d6accfcd0d94a04a5267dc481f5c7bc2b0db6adc2bd17b1f029) and what's displayed on the dcrandroid app (https://play.google.com/store/apps/details?id=com.decred.dcrandroid.testnet). I'll share a screenshot of the transaction page on the app in a bit

> * What will the input to the command be? A transaction hash?

Yes. Unless there's something else we can use to uniquely identify a transaction

**Comment by barisere** [comment]
> Compare what's displayed on decred explorer (ex. https://testnet.dcrdata.org/tx/2d574a40dbc31d6accfcd0d94a04a5267dc481f5c7bc2b0db6adc2bd17b1f029) and what's displayed on the dcrandroid app (https://play.google.com/store/apps/details?id=com.decred.dcrandroid.testnet). I'll share a screenshot of the transaction page on the app in a bit

Is every piece of information there needed in the CLI output?

**Comment by barisere** [comment]
Here is what I suggest for the command line output of transaction details. It includes most of the information shown on the decred explorer.
How does it look? Is there too much information in the output? What should be removed?

![Suggested transaction details output](https://user-images.githubusercontent.com/20553476/50450530-fd0acd80-092e-11e9-8fb3-674982b07e8d.png)

**Comment by itswisdomagain** [comment]
Looks good. But maybe too detailed? I'm thinking we could remove the inputs and outputs section and only show them when the command is issued with a flag say `-d/--detailed`

It'd help to compare what we have on dcrandroid

**Comment by itswisdomagain** [comment]
For context, this is how the transaction page looks on dcrandroid:
![screenshot 2018-12-27 at 9 21 37 pm](https://user-images.githubusercontent.com/18400051/50551762-6881d180-0c86-11e9-9206-2009a526cc27.png)

![screenshot 2018-12-27 at 9 45 39 pm](https://user-images.githubusercontent.com/18400051/50551756-5d2ea600-0c86-11e9-9dab-62e522a02481.png)
