### ISSUE TITLE
close connection dcrwallet rpc properly

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#81]
Add code to properly terminate the opened connection to dcrwallet daemon over rpc after running a cli command or after the http server is shutdown

The connection is currently auto-terminated but a proper cleanup and shutdown is in order

**Comment by barisere** [comment]
Grpc handles the RPC life cycle itself, so the underlying connection is closed once the RPC terminates.

**Comment by itswisdomagain** [comment]
Yeah, true.
I'm gonna close this issue for now until a more concrete need for a shutdown functionality is evident. I think the addition of mobilewallet mode (#60) may be provide that need. But let's get there first
