### ISSUE TITLE
ask to start dcrwallet if it isn't currently running

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#90]
If godcr is run with `usedcrwallet=true` but a dcrwallet rpc connection cannot be established, it might be because dcrwallet is not running.

The following confirmation should be requested from the user, after which `godcr` should start `dcrd` and `dcrwallet`:
```
There is no dcrwallet process started, would you like godcr to run the process? [Y/n]
```

It's important to note that 
- A dcrwallet rpc connection failure doesn't always mean a dcrwallet process is not running
- It could be because the rpc server address was not set by the user
- #152 takes care of that scenario. But before a fix for #152 is merged, the absence of rpc server address in config should not be taken to mean that dcrwallet is not started
- Instead, it's necessary to first confirm that dcrwallet is not running by checking for it in the list of processes running in the user's PC before asking the user if to start dcrwallet
- If dcrwallet is found to be running, the user should instead be asked to enter a valid server address. See the concluding part of https://github.com/raedahgroup/godcr/issues/152#issue-397480805

**Comment by barisere** [comment]
`dcrwallet` requires on `dcrd`. Should both processes be started?
Also `dcrlibwallet` is now the default wallet provider, so is this still relevant?

**Comment by itswisdomagain** [comment]
> Also `dcrlibwallet` is now the default wallet provider, so is this still relevant?

Yes, but only comes into play if a user choses to connect to dcrwallet rpc. I'll update this issue's description in a moment

> `dcrwallet` requires on `dcrd`. Should both processes be started?

Whatevers required to get dcrwallet running, as long as it is doable and doesn't cause problems for the user
