### ISSUE TITLE
dcrwallet returns incorrect data for a transaction's block hash

### ISSUE THREAD

**Issue by barisere** [raedahgroup/godcr-old#96]
On [PR 83](http://github.com/raedahgroup/godcr/pull/83), the block hash returned by dcrwallet is the same as the transaction hash. This has been confirmed as a bug on the dcrwallet project, and [an issue has been submitted](https://github.com/decred/dcrwallet/issues/1365). This bug shall be documented for now, and this issue shall await a fix from the dcrwallet project.

**Comment by barisere** [comment]
This issue has been fixed in dcrwallet https://github.com/decred/dcrwallet/pull/1367. You need to update `dcrwallet`, and maybe `dcrd`, to get the fix; updating both to the latest versions worked for me.  See the output now has a correct block hash.
```
$ ./godcr show-transaction dc8f20a53ab10246abf19b78296e183f7cdd84040f48f3fd8b05b21068e33ca1
Looking for wallets...
Hash              dc8f20a53ab10246abf19b78296e183f7cdd84040f48f3fd8b05b21068e33ca1
Confirmations     1528
Included in block 000000000022476e6de9b642986624d87e7fd05e18b7cebdd5cca5a82dac1049
Type              REVOCATION
Amount sent       0 DCR
Date              Fri Jan 4, 2019 6:48PM
Size              0.2 kB
Fee               0.00022 DCR
Rate              0.00101851 DCR/kB
```

**Comment by itswisdomagain** [comment]
Latest `dcrd` and `dcrwallet` binaries are available for download [here: https://github.com/decred/decred-binaries/releases](https://github.com/decred/decred-binaries/releases)
